--- 
title: "STAT 720 - Design of Experiments"
author: "Josefina Lacasa"
date: Summer 2025 #"`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Welcome to STAT 720!  
June 9th, 2025  

## About this course:  

- [About me](https://jlacasa.github.io/) 
- About you: 
- What's your major, what do you expect to learn?

### Logistics  

- [Website](https://stat720.github.io/summer2025)
- Syllabus
- Statistical programming requirements  
- Rough mindmap of the course (on whiteboard)  
- [Semester project - design your own experiment.](https://stat720.github.io/2025summer/summer2025/notes/semester-project.html)   
- Grades: A (100-89.999999999(!!!)), B (89.99-79.99), C (79.99-69.99), D (69.99-59.99), F (<59.99).
- Attendance policies  

## Learning goals   

By the end of this course, you should be able to:  
- Be able to identify the treatment design and experiment design (and other components of the design).  
- Be able to write out the statistical model.  
- Know the benefits/disadvantages of different experiment designs.  


## On notation  

- scalars: $y$, $\sigma$, $\beta_0$  
- vectors: $\mathbf{y} \equiv [y_1, y_2, ..., y_n]'$, $\boldsymbol{\beta} \equiv [\beta_1, \beta_2, ..., \beta_p]'$, $\boldsymbol{u}$  
- matrices: $\mathbf{X}$, $\Sigma$  
- probability distribution: $y \sim N(0, \sigma^2)$, $\mathbf{y} \sim N(\boldsymbol{0}, \sigma^2\mathbf{I})$.     

## Why do designed experiments exist?  

### Example  

You want to bake cookies and are not sure about the amount of baking powder vs. baking soda. 

- more baking powder = smaller, more cakey cookies   
- more baking soda = larger, crispier cookies  

How can we estimate the cookie diameter 

> **Case A:**   
> Bake 3 cookies, each with a different levels of baking powder:baking soda ratio.
> 
> **Case B:**   
> - On Monday: Bake 3 cookies, each with a different levels of baking powder:baking soda ratio.     
> - On Tuesday: Bake 3 cookies, each with a different levels of baking powder:baking soda ratio.     
> - On Wednesday: Bake 3 cookies, each with a different levels of baking powder:baking soda ratio.     
> 
> **Case C:**   
> - On Monday: Bake 3 cookies with the first level of baking powder:baking soda ratio.     
> - On Tuesday: Bake 3 cookies with the second level of baking powder:baking soda ratio.     
> - On Wednesday: Bake 3 cookies with the third level of baking powder:baking soda ratio.     
> 
> Group discussion: which is preferrable?  


## The golden rules of designed experiments  

- Randomization  
- Replication  
- Local control  

## Concepts in designed experiments  
- Experimental unit: smallest unit to which a treatment is independently assigned/applied. 
- Observational unit: smallest unit on which observations are made. 

